export const LoginUser=async(req,res)=>{
    try {
        res.send("Im in controller");
    } catch (error) {
        console.log(`Error in User Controller ${error}`);
    }
}
export const registerUser=async(req,res)=>{
    try {
        res.send("Im in controller");
    } catch (error) {
        console.log(`Error in User Controller ${error}`);
    }
}